http:
  baseUrl: "http://192.168.100.203:8000/"
  authUsername: ""
  authPassword: ""

protocol: "udpv4"

agent1:
  endpointAddress: "192.168.100.203"
  endpointPort:
    - 6666
agent2:
  endpointAddress: "192.168.100.203"
  endpointPort:
    - 6667

rootDataDir: "management-api-test/"

testTag: "management-api-test"