baseUrl: "http://192.168.100.203:8000/"
httpAuthUsername: ""
httpAuthPassword: ""

protocol: "udpv4"

agent1:
  endpointAddress: "192.168.100.203"
  endpointPort: 6666
agent2:
  endpointAddress: "192.168.100.203"
  endpointPort: 6667

dataDirRoot: "management-api-test/"