http:
  baseUrl: "http://192.168.100.203:8001/"
  authUsername: ""
  authPassword: ""

protocol: "udpv4"

agent1:
  endpointAddress: "192.168.100.203"
  endpointPort:
    - 6668
    - 7000

rootDataDir: "metrics-api-test/"